/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.br.tads.locadora.view;

/**
 *
 * @author nilo-
 */
public class TabbedView extends javax.swing.JPanel {

    /**
     * Creates new form TabbedView
     */
    public TabbedView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        clienteComponent1 = new com.br.tads.locadora.view.ClienteComponent();
        veiculosComponent1 = new com.br.tads.locadora.view.VeiculosComponent();
        locacaoComponent1 = new com.br.tads.locadora.view.LocacaoComponent();
        devolucaoComponent2 = new com.br.tads.locadora.view.DevolucaoComponent();
        vendasComponent1 = new com.br.tads.locadora.view.VendasComponent();

        jTabbedPane1.addTab("Clientes", clienteComponent1);
        jTabbedPane1.addTab("Veiculos", veiculosComponent1);
        jTabbedPane1.addTab("Locação", locacaoComponent1);
        jTabbedPane1.addTab("Devolução", devolucaoComponent2);
        jTabbedPane1.addTab("Vender", vendasComponent1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.br.tads.locadora.view.ClienteComponent clienteComponent1;
    private com.br.tads.locadora.view.DevolucaoComponent devolucaoComponent2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.br.tads.locadora.view.LocacaoComponent locacaoComponent1;
    private com.br.tads.locadora.view.VeiculosComponent veiculosComponent1;
    private com.br.tads.locadora.view.VendasComponent vendasComponent1;
    // End of variables declaration//GEN-END:variables
}
